# Generated by Django 4.2.6 on 2024-02-21 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signupform', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sgform',
            name='emailotp',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sgform',
            name='photp',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
