# Generated by Django 4.2.6 on 2024-02-22 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signupform', '0003_remove_sgform_emailotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='sgform',
            name='emailotp',
            field=models.CharField(default='0000', max_length=10),
        ),
    ]
