# Generated by Django 4.2.6 on 2024-02-22 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signupform', '0004_sgform_emailotp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sgform',
            name='photp',
        ),
        migrations.AlterField(
            model_name='sgform',
            name='emailotp',
            field=models.CharField(max_length=10),
        ),
    ]
