# Generated by Django 4.2.6 on 2024-02-22 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signupform', '0005_remove_sgform_photp_alter_sgform_emailotp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sgform',
            name='emailotp',
            field=models.CharField(max_length=30),
        ),
    ]
