# Generated by Django 4.2.6 on 2024-02-23 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signupform', '0006_alter_sgform_emailotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='sgform',
            name='photp',
            field=models.CharField(default='', max_length=10),
        ),
    ]
